# Generated by Django 3.0.4 on 2020-03-24 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created On', models.DateField(auto_now_add=True)),
                ('Bill No', models.CharField(max_length=20)),
                ('Bill date', models.DateField()),
                ('Goods Value', models.IntegerField()),
                ('Discount %', models.IntegerField(blank=True)),
                ('IGST', models.IntegerField(blank=True)),
                ('CGST', models.IntegerField(blank=True)),
                ('SGST', models.IntegerField(blank=True)),
                ('Total Value', models.IntegerField()),
                ('LR No', models.CharField(max_length=30)),
                ('LR date', models.DateField()),
                ('Fright', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Booking Station', models.CharField(blank=True, max_length=20)),
                ('Delivery date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Transport')),
            ],
        ),
    ]
