# Generated by Django 3.0.4 on 2020-03-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_purchaseentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Discount %',
            new_name='Discount',
        ),
    ]
