# Generated by Django 2.2.4 on 2020-03-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200324_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseentry',
            name='Total Value',
        ),
    ]
