# Generated by Django 2.2.4 on 2020-03-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_purchaseentry_total value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Bill date',
            new_name='bill_date',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Bill No',
            new_name='bill_no',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Booking Station',
            new_name='booking_station',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='CGST',
            new_name='c_gst_tax',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Created On',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Delivery date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Fright',
            new_name='fright',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='Goods Value',
            new_name='goods_val',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='IGST',
            new_name='i_gst_tax',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='LR date',
            new_name='lr_date',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='LR No',
            new_name='lr_no',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='SGST',
            new_name='s_gst_tax',
        ),
    ]
