# Generated by Django 2.2.4 on 2020-03-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200326_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentry',
            name='c_gst_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='s_gst_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
