# Generated by Django 2.2.4 on 2020-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200327_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='discount',
            new_name='discount_percent',
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='discount_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
