# Generated by Django 2.2.4 on 2020-03-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200327_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='discount_percent',
            new_name='d_percent',
        ),
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='discount_value',
            new_name='d_value',
        ),
    ]
