# Generated by Django 2.2.4 on 2020-03-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200327_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=20)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('NEFT', 'NEFT')], max_length=256)),
                ('cheque_no', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Bank')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier')),
            ],
        ),
    ]
